---
- name: install Xorg
  pacman:
      name:
          - xorg-server #graphical server
          - xorg-xinit  #start the graphical server
          - xorg-xprop  #detect window properties
          - xorg-xdpyinfo  #aids with resolution determination and screen recording
          - xorg-xbacklight  #enable changing screen brightness level

          ### Void ??????
          # - xorg-xmodmap
          # - xorg-xsetroot
          # - xorg-xset

          - xcompmgr
          - xwallpaper

          - libnotify
          - dunst #suckless notification system
          - sxhkd #bind keys
          - unclutter #hide an inactive mouse

          - xclip #allows for copying and pasting from command line
          - xcape # gives the special escape/super mappings of LARBS
          - xdotool # provides window action utilities on the command line

          - slock
            ##not sure about this one
          - arandr #is a UI for screen adjustment.

            ### music player
            # - mpd
            # - mpc
            # - mpv
      state: present


