---
- name: Install tmux
  pacman:
    name:
        - tmux
        - fzf #is a fuzzy finder tool.
        - the_silver_searcher # grep but better
    state: present

- name: Install ranger and ctags
  aur:
    name:
        - ranger-git
        - ctags
  become: true
  become_user: aur_builder



- include: st.yml
- include: zsh.yml
